### ISSUE TITLE
Update to support test262 version 3.0.0

### ISSUE THREAD

**Issue by pmdartus** [bocoup/test262-stream#14]
See recent version bump to `3.0.0`: https://github.com/tc39/test262/commit/8dbeb27b59d835311868fe6793f8efad2e5855be

**Comment by jugglinmike** [comment]
Thanks for the reminder! A patch for this is currently under review:

https://github.com/bocoup/test262-stream/pull/15

As noted there, Test262 version 3 doesn't introduce any new rules for source text modifications. In other words, it's safe for you to override `test262-stream`'s warning with the `acceptVersion` option while you wait. The project's readme file has more information about the option; please let us know if that doesn't work for you.

**Comment by adrianheine** [comment]
I think this can be closed, at least when you publish a new release.

**Comment by jugglinmike** [comment]
You bet! Version 1.2.0 is now available:

- https://www.npmjs.com/package/test262-stream
- https://github.com/bocoup/test262-stream/tree/v1.2.0
